In [1]:
#Boosting Technique : -
#1. ADA Boost : Adaptor Boosting
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
#To load dataset bank.csv
df=pd.read_csv("heart.csv")
#to display first 5 records
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [3]:
#Check null values in given dataset
df.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [4]:
df.dtypes

age           int64
sex           int64
cp            int64
trestbps      int64
chol          int64
fbs           int64
restecg       int64
thalach       int64
exang         int64
oldpeak     float64
slope         int64
ca            int64
thal          int64
target        int64
dtype: object

In [5]:
#Check Either data is balance or not 
df['target'].value_counts()

target
1    165
0    138
Name: count, dtype: int64

In [6]:
#Select input and output from dataset
X=df.drop("target",axis=1)#input
Y=df['target']#output

In [7]:
#train test split
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,
                        test_size=0.3,random_state=1)

In [8]:
#Apply scaling
from sklearn.preprocessing import StandardScaler
#create the object of StandardScaler class
ss=StandardScaler()
X_train=ss.fit_transform(X_train)
X_test=ss.transform(X_test)

In [9]:
#Create user defined function
def create_model(model): #here model passing argument(object)
    model.fit(X_train,Y_train)#train the model with 70%data
    #to test the model with 30% data
    Y_pred=model.predict(X_test)
    #to generate report and confusion matrix
    print(classification_report(Y_test,Y_pred))
    print(confusion_matrix(Y_test,Y_pred))
    return model

In [10]:
from sklearn.metrics import classification_report,confusion_matrix

In [11]:
#create a baseline model : Logistic Regression
from sklearn.linear_model import LogisticRegression

In [12]:
#create object of class LogisticRegression
lr=LogisticRegression()

In [13]:
#call function
lr=create_model(lr)

              precision    recall  f1-score   support

           0       0.77      0.73      0.75        41
           1       0.79      0.82      0.80        50

    accuracy                           0.78        91
   macro avg       0.78      0.78      0.78        91
weighted avg       0.78      0.78      0.78        91

[[30 11]
 [ 9 41]]


In [14]:
#DecisionTreeClassifier

In [15]:
#Pruning Technique

In [16]:
#RandomForestClassifier

In [17]:
#Boosting Technique 
#ADA Boost 
from sklearn.ensemble import AdaBoostClassifier

In [18]:
#create the object of AdaBoostClassifier class
ada=AdaBoostClassifier(n_estimators=6,random_state=1)
#n_estimators means no. of decision tree (depend on no. of input features)

In [19]:
#call function
ada=create_model(ada)

              precision    recall  f1-score   support

           0       0.82      0.76      0.78        41
           1       0.81      0.86      0.83        50

    accuracy                           0.81        91
   macro avg       0.81      0.81      0.81        91
weighted avg       0.81      0.81      0.81        91

[[31 10]
 [ 7 43]]


In [20]:
#2. Gradient Boosting : -
#2. Gradient Boosting(GB) : - 
#Its basically focus on short comings error  means fully grown tree 
#error means residual =actual output-predicted output

#2. gradient Boost technuique : second tech. of Boosting Ensembling technique 
# GB  : - its create a fully grown tree.this algorithm is focus on short comings 
#short comings means error 

In [21]:
#call GradientBoostingClassifier class from following package
from sklearn.ensemble import GradientBoostingClassifier

In [22]:
#create the object of GradientBoostingClassifier class
gbc=GradientBoostingClassifier(n_estimators=19,random_state=1)
##not can be <=100

In [23]:
#call function 
gbc=create_model(gbc)

              precision    recall  f1-score   support

           0       0.74      0.71      0.72        41
           1       0.77      0.80      0.78        50

    accuracy                           0.76        91
   macro avg       0.76      0.75      0.75        91
weighted avg       0.76      0.76      0.76        91

[[29 12]
 [10 40]]


In [24]:
#3. Extreme Gradient Boosting (XGB):- 
#3. Extreame Gradient Boosting  : 3rd technique of Boosting 
#This is better version of gradient boosting . . short form XGB 
#why call better version of Gradient Boosting : -
#1. XG Bossting use : - Multithreading technique(parallel processing)
#2. It takes less memory space and faster 
#3. It is very useful to handle huge amt of data .Its deal large amount of data
#4. Its handle outlier because have inbuilt capability
#5. Its handle null values 
#6. Its handle automatic overfitting situation .

In [25]:
#install the external package from python's community first for XGBoost
#!pip install xgboost 

In [26]:
from xgboost import XGBClassifier

In [27]:
#create object of class XGBClassifier
xgc=XGBClassifier(n_estimators=10,reg_alpha=1)
#reg means regularation : lambda or alpha
#automatic overfitting : reg means regularation and alpha or lambda : 
#hyperparameter
#1 means True

In [28]:
#call function
xgc=create_model(xgc)

              precision    recall  f1-score   support

           0       0.72      0.68      0.70        41
           1       0.75      0.78      0.76        50

    accuracy                           0.74        91
   macro avg       0.73      0.73      0.73        91
weighted avg       0.74      0.74      0.74        91

[[28 13]
 [11 39]]
