In [1]:
 #First import all basic libraries
import pandas as PD
import numpy as NP
import matplotlib.pyplot as MPL
import seaborn as SB
import warnings
warnings.filterwarnings('ignore')
import tensorflow as TF

In [2]:
#Load Dataset
CR_FD = PD.read_csv("/content/drive/MyDrive/DEEP LEARNING/creditcard.csv")
CR_FD.sample(9)

Time        V1        V2        V3        V4        V5        V6  \
239736  150237.0  2.060955 -0.087013 -1.071585  0.423605 -0.193490 -1.231025   
100792   67624.0 -1.453563  0.256900  1.026045  1.227140  0.621816  0.140321   
256794  157864.0  2.038941  0.241511 -2.794134  1.157233  1.326883 -0.109780   
273113  165427.0  2.007839 -0.305715 -0.484716  0.331294 -0.270266  0.014489   
172402  121088.0 -0.100969  1.425898 -1.902412 -0.826365  0.727033 -0.226592   
112796   72809.0 -0.641061 -0.427413  1.164048  0.838731 -1.063626  0.425806   
62180    50165.0  1.137152  0.134520  0.196730  0.955990 -0.180340 -0.449203   
270949  164342.0 -1.644534 -0.305258  1.825990 -0.407615  0.825329 -0.415748   
49386    44035.0 -0.092847  1.137565  1.253136  2.005960  0.778232  0.436899   

              V7        V8        V9  ...       V21       V22       V23  \
239736  0.150937 -0.306995  0.617249  ... -0.294367 -0.738843  0.347207   
100792 -0.241843  0.517888 -0.642355  ...  0.200256  0.501813  0.113239   
256794  0.389111  0.018821  0.314203  ... -0.077600 -0.190487 -0.107994   
273113 -0.551448 -0.041364  1.231981  ...  0.186607  0.838059  0.097391   
172402 -1.052784 -5.666703 -0.740262  ... -2.337642  1.325933  0.084485   
112796  0.849339  0.087597 -1.256331  ... -0.223731 -0.468375  0.527530   
62180   0.110193 -0.016425 -0.153566  ... -0.105484 -0.459330 -0.054167   
270949  0.058989  0.072418 -0.042421  ... -0.131465 -0.279544 -0.438399   
49386   0.497463  0.109612 -1.602497  ...  0.035774  0.058939 -0.098396   

             V24       V25       V26       V27       V28  Amount  Class  
239736  0.032514 -0.316703  0.197053 -0.074053 -0.060897    1.98      0  
100792 -0.740878 -0.170015 -0.216513 -0.019362  0.047170   27.55      0  
256794 -0.549251  0.498880 -0.468905 -0.024522 -0.046451   17.18      0  
273113  0.541809  0.017888 -0.235721  0.046990 -0.028835    9.99      0  
172402  0.595698  0.556708  0.127174  0.065539  0.351268    7.63      0  
112796 -0.025806 -0.230298 -0.240602  0.112758  0.162172  249.55      0  
62180  -0.034960  0.480227 -0.524949 -0.000886  0.017088   46.32      0  
270949 -0.331543  0.366299 -0.728682  0.164486 -0.019817  100.00      0  
49386  -0.524033 -0.394819 -0.076865  0.089866  0.070062    5.48      0  

[9 rows x 31 columns]

In [3]:
#Data Preprocessing
#Check null values.
CR_FD.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [4]:
CR_FD.duplicated().sum()

1081

In [5]:
#To remove duplicate row
CR_FD.drop_duplicates(inplace=True)

In [6]:
CR_FD.duplicated().sum()

0

In [7]:
CR_FD.dtypes

Time      float64
V1        float64
V2        float64
V3        float64
V4        float64
V5        float64
V6        float64
V7        float64
V8        float64
V9        float64
V10       float64
V11       float64
V12       float64
V13       float64
V14       float64
V15       float64
V16       float64
V17       float64
V18       float64
V19       float64
V20       float64
V21       float64
V22       float64
V23       float64
V24       float64
V25       float64
V26       float64
V27       float64
V28       float64
Amount    float64
Class       int64
dtype: object

In [8]:
#Check balance of dataset.
CR_FD['Class'].value_counts()

0    283253
1       473
Name: Class, dtype: int64

In [9]:
CR_FD
IP = CR_FD.drop(['Class'],axis=1)
OP = CR_FD['Class']

In [10]:
#Train test split
from sklearn.model_selection import train_test_split
I_P_train,I_P_test,O_P_train,O_P_test=train_test_split(IP,OP,test_size=0.3,random_state=1)

In [11]:
#Training the standard scalar on I_P_train and I_P_test input data.
from sklearn.preprocessing import StandardScaler
#Create object of StandardScaler class
S_S = StandardScaler()
I_P_train=S_S.fit_transform(I_P_train)
I_P_test=S_S.transform(I_P_test)

In [12]:
I_P_train.shape

(198608, 30)

In [13]:
#Clearly Data is imbalance
#Here, there are 2 classes : first class : 0 means income <50k
#and second class : 1 means Income>=50k
#here majority class : 0 and minority class : 1
#Here we have to balance of both classes
#means here we have to use sampling technique for baqlance of 2 classes
#There are 2 types of sampling technique :-
#1. RandomOverSampling : in this sampling , converts minority class into
#majority class
#2. RandonUnderSampling : in this sampling , converts majority class into
#minority class

In [14]:
#First install inbuilt package imblearn
!pip install imblearn
#Random oversampler : To create duplicate Minor samplings to meet the no. of major samplings.
from imblearn.over_sampling import RandomOverSampler
#Apply RandomOverSampler
#First create an object
R_O_S = RandomOverSampler()

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [15]:
#Resampling the training samples
IP_train_S,OP_train_S=R_O_S.fit_resample(I_P_train,O_P_train)

In [16]:
#Resampling the testing samples
IP_test_S,OP_test_S=R_O_S.fit_resample(I_P_test,O_P_test)

In [17]:
IP.shape

(283726, 30)

In [18]:
IP.shape[1]

30

In [42]:
# to apply regularization :
from tensorflow.keras import regularizers
# regularizers is method of keras
#create object of Sequential class
model=TF.keras.models.Sequential([
  TF.keras.layers.Dense(units=72,activation='relu',input_shape=(IP.shape[1],),
   kernel_regularizer = regularizers.l2(0.21)),TF.keras.layers.Dropout(0.5),
  #first hidden layer
  TF.keras.layers.Dense(units=72,activation='relu',
  kernel_regularizer = regularizers.l2(0.21)), #hidden layer2
  TF.keras.layers.Dropout(0.5),
  TF.keras.layers.Dense(units=36,activation='relu',kernel_regularizer = regularizers.l2(0.01)),TF.keras.layers.Dropout(0.30),
  #hidden layer3
  TF.keras.layers.Dense(units=1,activation='sigmoid',kernel_regularizer = regularizers.l1(0.01))
])

In [43]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_6 (Dense)             (None, 72)                2232      
                                                                 
 dropout_4 (Dropout)         (None, 72)                0         
                                                                 
 dense_7 (Dense)             (None, 72)                5256      
                                                                 
 dropout_5 (Dropout)         (None, 72)                0         
                                                                 
 dense_8 (Dense)             (None, 36)                2628      
                                                                 
 dropout_6 (Dropout)         (None, 36)                0         
                                                                 
 dense_9 (Dense)             (None, 1)                

In [44]:
#Compile the model
model.compile(optimizer='Adam',loss='binary_crossentropy',metrics=['accuracy'])

In [45]:
#Early Stopping :
from tensorflow.keras.callbacks import EarlyStopping            
#callbacks inbuilt parameter of fit() 
#create callback : Call_B -
#EarlyStopping() inbuilt function
Call_B=EarlyStopping(
    monitor="val_loss",  #val_loss means testing error
    min_delta=0.00001, #value of lambda 
    patience=20,
    verbose=1,
    mode="auto", #min loss 
    baseline=None,
    restore_best_weights=False
)

In [46]:
#Train the model,use inbuilt method fit()
Trained_Model = model.fit(IP_train_S,OP_train_S,epochs=5400,batch_size=100,validation_data=(IP_test_S,OP_test_S),callbacks = Call_B)
#Trained_Model user defined object

Epoch 1/5400
3966/3966 [==============================] - 15s 4ms/step - loss: 0.8233 - accuracy: 0.9304 - val_loss: 0.4216 - val_accuracy: 0.8947
Epoch 2/5400
3966/3966 [==============================] - 14s 3ms/step - loss: 0.3660 - accuracy: 0.9341 - val_loss: 0.3970 - val_accuracy: 0.8980
Epoch 3/5400
3966/3966 [==============================] - 14s 3ms/step - loss: 0.3570 - accuracy: 0.9340 - val_loss: 0.3972 - val_accuracy: 0.8970
Epoch 4/5400
3966/3966 [==============================] - 13s 3ms/step - loss: 0.3566 - accuracy: 0.9339 - val_loss: 0.4007 - val_accuracy: 0.8950
Epoch 5/5400
3966/3966 [==============================] - 14s 3ms/step - loss: 0.3564 - accuracy: 0.9339 - val_loss: 0.3973 - val_accuracy: 0.8942
Epoch 6/5400
3966/3966 [==============================] - 14s 3ms/step - loss: 0.3566 - accuracy: 0.9339 - val_loss: 0.3962 - val_accuracy: 0.9011
Epoch 7/5400
3966/3966 [==============================] - 14s 3ms/step - loss: 0.3566 - accuracy: 0.9339 - val_loss: 0

In [47]:
model.evaluate(IP_train_S,OP_train_S)

12392/12392 [==============================] - 21s 2ms/step - loss: 0.3360 - accuracy: 0.9397


[0.336031049489975, 0.9396953582763672]

In [48]:
model.evaluate(IP_test_S,OP_test_S)

5313/5313 [==============================] - 9s 2ms/step - loss: 0.4008 - accuracy: 0.8964


[0.40075135231018066, 0.8963914513587952]

In [49]:
#Find the prediction means test the model
OP_pred = model.predict(IP_test_S).round(3)
OP_pred

array([[0.108],
       [0.084],
       [0.181],
       ...,
       [1.   ],
       [1.   ],
       [0.422]], dtype=float32)

In [50]:
OP_pred = NP.where(OP_pred>=0.5,1,0)
OP_pred

array([[0],
       [0],
       [0],
       ...,
       [1],
       [1],
       [0]])

In [54]:
#Print Report 
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(OP_test_S,OP_pred))
print(confusion_matrix(OP_test_S,OP_pred))

              precision    recall  f1-score   support

           0       0.83      0.99      0.91     84993
           1       0.99      0.80      0.89     84993

    accuracy                           0.90    169986
   macro avg       0.91      0.90      0.90    169986
weighted avg       0.91      0.90      0.90    169986

[[84540   453]
 [17159 67834]]
