In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb
import warnings
warnings.filterwarnings('ignore')

In [2]:
# To load Dataset
df=pd.read_csv("heart.csv")

In [3]:
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [4]:
#here target is output variable
df['target'].value_counts()

target
1    165
0    138
Name: count, dtype: int64

In [5]:
df.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [6]:
df.dtypes

age           int64
sex           int64
cp            int64
trestbps      int64
chol          int64
fbs           int64
restecg       int64
thalach       int64
exang         int64
oldpeak     float64
slope         int64
ca            int64
thal          int64
target        int64
dtype: object

In [7]:
# to check duplicate
df.duplicated().sum()

1

In [8]:
#to remove duplicate rows
df.drop_duplicates(inplace=True)

In [9]:
# to check duplicate
df.duplicated().sum()

0

In [10]:
#separate input and output from dataframe df_new
X=df.drop("target",axis=1)  #select input
Y=df['target']  #output

In [11]:
#train test split 70% and 30%
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.3,random_state=1)

In [12]:
X_train.shape,X_test.shape

((211, 13), (91, 13))

In [13]:
#Apply Standard Scaler on X_train and X_test 
from sklearn.preprocessing import StandardScaler
#create object of StandardScaler class
ss=StandardScaler()
X_train=ss.fit_transform(X_train)
X_test=ss.transform(X_test)#Apply Standard Scaler on X_train and X_test 


In [14]:
X_train

array([[-1.06167727, -1.55023411,  1.02938967, ..., -0.69616283,
         0.27995117, -0.51005185],
       [ 0.43317242,  0.64506386, -0.92737808, ...,  0.95429062,
        -0.72123014,  1.12056846],
       [ 0.43317242, -1.55023411, -0.92737808, ..., -0.69616283,
         1.28113248, -2.14067216],
       ...,
       [-2.66330193,  0.64506386,  0.05100579, ...,  0.95429062,
        -0.72123014, -0.51005185],
       [ 0.43317242,  0.64506386, -0.92737808, ...,  0.95429062,
         1.28113248,  1.12056846],
       [ 0.00607251,  0.64506386,  1.02938967, ...,  0.95429062,
        -0.72123014,  1.12056846]])

In [15]:
X.columns

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal'],
      dtype='object')

In [16]:
#Apply PCA , inbuilt class PCA --> define in decomposition outer class 
from sklearn.decomposition import PCA

In [17]:
#create object of PCA class
pc=PCA(n_components=None,random_state=1)
#n_components inbuilt parameter of PCA ,here pass no. of inputs 
# here no. of inputs =13
#None means pass all inputs

In [18]:
#use fit_transform() inbuilt method of PCA class on training input
# and transform() inbuit method of PCA class on testing data
X_train_pc=pc.fit_transform(X_train)
X_test_pc=pc.transform(X_test)

In [19]:
# to dhow variance of all inputs means all features , use inbuilt attributes
# explained_variance_ratio_ of PCA class
pc.explained_variance_ratio_

array([0.21426812, 0.11809512, 0.09805128, 0.09146624, 0.08003705,
       0.07043755, 0.06478328, 0.05720799, 0.05453809, 0.04814294,
       0.04170964, 0.03278829, 0.0284744 ])

In [20]:
#0.21426812+0.11809512+0.09805128+0.09146624 = 0.52
#Atleast 4 inputs

In [22]:
#train the model with LogisticRegression
from sklearn.linear_model import LogisticRegression

In [23]:
from sklearn.metrics import classification_report,confusion_matrix
'''for col in range(4,14):
    #create object of PCA class
    pc=PCA(n_components=col,random_state=1)
    X_train_pc=pc.fit_transform(X_train)
    X_test_pc=pc.transform(X_test)
    # train the model with LogisticRegression
    # create object of LogisticRegression class
    lr=LogisticRegression()
    lr.fit(X_train_pc,Y_train) #train the model with 70% data
    #to test the model , use inbuilt method predict() of LogisticRegression class
    Y_pred=lr.predict(X_test_pc)
    print("No. of features : ",col)
    print(classification_report(Y_test,Y_pred))
    print(confusion_matrix(Y_test,Y_pred))
    print()'''
    

    

No. of features :  4
              precision    recall  f1-score   support

           0       0.79      0.79      0.79        38
           1       0.85      0.85      0.85        53

    accuracy                           0.82        91
   macro avg       0.82      0.82      0.82        91
weighted avg       0.82      0.82      0.82        91

[[30  8]
 [ 8 45]]

No. of features :  5
              precision    recall  f1-score   support

           0       0.79      0.79      0.79        38
           1       0.85      0.85      0.85        53

    accuracy                           0.82        91
   macro avg       0.82      0.82      0.82        91
weighted avg       0.82      0.82      0.82        91

[[30  8]
 [ 8 45]]

No. of features :  6
              precision    recall  f1-score   support

           0       0.81      0.79      0.80        38
           1       0.85      0.87      0.86        53

    accuracy                           0.84        91
   macro avg       0.83  

In [24]:
#create object of PCA  class
pc=PCA(n_components=6,random_state=1)
X_train_pc=pc.fit_transform(X_train)
X_test_pc=pc.transform(X_test)
#train the model with LogisticRegression class
#create object of LogisticRegression class
lr=LogisticRegression()
lr.fit(X_train_pc,Y_train) #train the model with 70% data
#to test the model , use inbuilt method predict() of 
#LogisticRegression class
Y_pred=lr.predict(X_test_pc)
    
print(classification_report(Y_test,Y_pred))
print(confusion_matrix(Y_test,Y_pred))

              precision    recall  f1-score   support

           0       0.81      0.79      0.80        38
           1       0.85      0.87      0.86        53

    accuracy                           0.84        91
   macro avg       0.83      0.83      0.83        91
weighted avg       0.83      0.84      0.83        91

[[30  8]
 [ 7 46]]
